### ISSUE TITLE
Multiple Viewer instances render the same pdf

### ISSUE THREAD

**Issue by gridchin** [react-pdf-viewer/react-pdf-viewer#1033]
We are unable to render multiple PDFs on the same page, always renders the same one.

![image](https://user-images.githubusercontent.com/521282/156774915-7ade1833-146e-490b-aa43-617ea0dae1e4.png)

**Comment by phuoc-ng** [comment]
@gridchin Please upgrade to the latest version. This issue was fixed in v3.1.0.
Also, it's recommended to wrap the `Viewer` with plugins in a separated component. So the plugins aren't shared between multiple `Viewer` instance.

```tsx
// Don't
const defaultLayoutPluginInstance = defaultLayoutPlugin();

<Viewer fileUrl={file1} plugins={[defaultLayoutPluginInstance]} />

<Viewer fileUrl={file2} plugins={[defaultLayoutPluginInstance]} />
```

Instead, create a wrapper:

```tsx
// Do
const ViewerWrapper: React.FC<{ fileUrl: string }> = ({ fileUrl }) => {
    const defaultLayoutPluginInstance = defaultLayoutPlugin();

    return (        
       <Viewer fileUrl={fileUrl} plugins={[defaultLayoutPluginInstance]} />
    );
};

// Then use the wrapper in the sample page such as
<ViewerWrapper fileUrl={file1} />
<ViewerWrapper fileUrl={file2} />
```

![Screen Shot 2022-03-05 at 09 51 46](https://user-images.githubusercontent.com/57786711/156865169-904e8c5d-6694-426a-9e32-d126ea4e8cc0.png)

**Comment by phuoc-ng** [comment]
I add a new documentation page for it at https://react-pdf-viewer.dev/examples/use-multiple-viewers-in-the-same-page/

**Comment by gridchin** [comment]
Thank you @phuoc-ng
