### ISSUE TITLE
Open file appears on responsive menu

### ISSUE THREAD

**Issue by puera** [react-pdf-viewer/react-pdf-viewer#1049]
I disable "Open File" with a transformToolBarslot, but the button "Open File"  still appears on responsive screen

```export default function Pdf({ fileUrl, preview = false }: Props) {
  const transform: TransformToolbarSlot = (slot: ToolbarSlot) => ({
    ...slot,
    Open: () => <></>
  });

  const renderToolbar = (Toolbar: (props: ToolbarProps) => ReactElement) => (
    <Toolbar>{renderDefaultToolbar(transform)}</Toolbar>
  );

  const defaultLayoutPluginInstance = defaultLayoutPlugin({
    renderToolbar
  });

  const { renderDefaultToolbar } =
    defaultLayoutPluginInstance.toolbarPluginInstance;
```

**Comment by phuoc-ng** [comment]
@puera The _More actions_ menu contains some identical slots. They are initially hidden but will be displayed under the More actions menu in the small screens. I updated the [documentation page](https://react-pdf-viewer.dev/examples/remove-some-parts-from-the-default-toolbar/).

So, in order to remove the `Open` functionality completely:

```jsx
const transform: TransformToolbarSlot = (slot: ToolbarSlot) => ({
    ...slot,
    Open: () => <></>,
    OpenMenuItem: () => <></>
});
```
