### ISSUE TITLE
Bigger thumbnail image?

### ISSUE THREAD

**Issue by mm105** [react-pdf-viewer/react-pdf-viewer#1106]
Is it possible to increase dimensions of thumbnail image? I can overwrite default CSS and increase width or height but than thumbnail is blurry since original resolution of image is smaller (width only 100px). This probably should then be done during process of creating thumbnail images. I don't see this option in documentation or examples. Can this feature be added? Thanks!

**Comment by phuoc-ng** [comment]
You're right. Currently, the width of thumbnails are fixed as `100px`. I will support this request!

**Comment by phuoc-ng** [comment]
@mm105 
The request was implemented in the latest code, and will be available in the next release.

```tsx
const thumbnailPluginInstance = thumbnailPlugin({
    thumbnailWidth: 150,
});

// Use with the default layout plugin
const defaultLayoutPluginInstance = defaultLayoutPlugin({
    thumbnailPlugin: {
        thumbnailWidth: 150,
    },
});
```

![Screen Shot 2022-04-30 at 18 34 11](https://user-images.githubusercontent.com/57786711/166218647-c4e78b00-f08f-451f-903f-875c17f36c22.png)

**Comment by mm105** [comment]
Great, thanks! Will it support width in percentages (e.g. "90%")?

**Comment by phuoc-ng** [comment]
[v3.3.1](https://react-pdf-viewer.dev/updates/) is released. Please upgrade if you already purchase.
I also added [examples](https://react-pdf-viewer.dev/examples/customize-the-width-of-thumbnails/) for the option.

Due to the canvas/image calculation, you have to specify the width in pixels. It's not possible to use percentages.
