### ISSUE TITLE
Building from source.

### ISSUE THREAD

**Issue by NigelCunningham** [react-pdf-viewer/react-pdf-viewer#331]
Hi there.

I'm seeking to add support for providing a password  when initialising the component (<PhuocngReactPdfView file={getFile(this)} password={getUpwd(this)}/>), but am having difficulty with building. I've forked your repo and added my modifications there, and am running npm link in the repo and in the website I'm working on to seek to test my changes.

In the forked repo I have invoked "npm run build"  but when I run "npm run build" in my project (a Drupal theme), I get lots of errors. I've done a fair bit of Googling, without success, so am hoping you'll be able to give me a push in the right direction. There a potential license in it if you need incentive! :)

```
ERROR in ./components/03-organisms/PhuocngReactPdfView/react/PhuocngReactPdfView.component.js
Module not found: Error: Can't resolve '@react-pdf-viewer/core' in '/path/to/theme/components/03-organisms/PhuocngReactPdfView/react'
resolve '@react-pdf-viewer/core' in '/path/to/theme/components/03-organisms/PhuocngReactPdfView/react'
  Parsed request is a module
  using description file: /path/to/theme/package.json (relative path: ./components/03-organisms/PhuocngReactPdfView/react)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /path/to/theme/components/03-organisms/PhuocngReactPdfView/react/node_modules doesn't exist or is not a directory
      /path/to/theme/components/03-organisms/PhuocngReactPdfView/node_modules doesn't exist or is not a directory
      /path/to/theme/components/03-organisms/node_modules doesn't exist or is not a directory
      /path/to/theme/components/node_modules doesn't exist or is not a directory
```
[...]
```
      looking for modules in /path/to/theme/node_modules
        using description file: /path/to/theme/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /path/to/theme/package.json (relative path: ./node_modules/@react-pdf-viewer/core)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
             /path/to/theme/node_modules/@react-pdf-viewer/core doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /path/to/theme/node_modules/@react-pdf-viewer/core.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
             /path/to/theme/node_modules/@react-pdf-viewer/core.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /path/to/theme/node_modules/@react-pdf-viewer/core.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /path/to/theme/node_modules/@react-pdf-viewer/core.json doesn't exist
            as directory
             /path/to/theme/node_modules/@react-pdf-viewer/core doesn't exist
[
```

**Comment by phuoc-ng** [comment]
Thanks for reaching out, @NigelCunningham 

Here is the steps that I hope you can build and play around with the source.

## Build from source

1. Fork the repos
2. Clone your forked repos to the local
3. From the cloned folder, run the command

```console
npm install
```

This command installs dependencies for all packages. After that, you should see the following folders

```
// For demo
demo/node_modules/@react-pdf-viewer/...

// The root folder
node_modules

// For packages
packages/attachment/node_modules
packages/bookmark/node_modules
...
```

4. Build the source

```console
npm run build
```

The command will build all packages in `packages` folder.
In each package, you will see the `lib` folder which is the same as you see in the npm package.

```
packages/attachment/lib/...
packages/bookmark/lib/...
...
```

If you open `demo/node_modules/@react-pdf-viewer`, you should see the `lib` in each package because they're actually shortcut (linked) version from the `packages`:

```
demo/node_modules/@react-pdf-viewer/core --> packages/core
demo/node_modules/@react-pdf-viewer/default-layout --> packages/default-layout
...
```

5. Test

* Go to the `demo` folder

```console
cd demo
```

* Run the command

```console
npm run dev
``` 

Webpack will bundle all the files, and you can visit http://localhost:8001/ to see the demo:

<img width="1260" alt="Screen Shot 2020-10-28 at 21 06 41" src="https://user-images.githubusercontent.com/57786711/97446888-86431f00-1961-11eb-964a-89be097d56ed.png">

If you go to this step without any problems, then congratulations!

6. Modify the source

* You can modify the source in `packages/PACKAGE_NAME_HERE/src`, and you can see the change on http://localhost:8001/ without having to rebuild the source.

* If you change the source, and expose/change some Typescript definitions, you have to rebuild the source (See step 4).

**Comment by phuoc-ng** [comment]
## Ask for feature/improvement

> I'm seeking to add support for providing a password when initialising the component

It's NOT recommended to modify the source directly, because the changes will be LOST when you upgrade to newer version of library.

I would like to know your specific problem/requirement in this use case, and will provide the best approach for you.

**Comment by NigelCunningham** [comment]
Thanks for the reply. I'm looking to be able to enhance it and integrate it fully with Drupal so that we can do things like having clickable links in search results beside the viewer that cause the viewer to load a new PDF and/or scroll to a particular page or bookmark, loading bookmarks and annotations and adding them to the PDF being viewed, using the PDF viewer to add annotations and storing them in Drupal and more.

I'm not worried about modifying the source - I understand how to create PRs and if necessary rebase and so on; it was just your switch to plugins that caused me grief because I'm not an expert with webpack.

Thanks again for the reply.
