### ISSUE TITLE
onPageChange fires more than once

### ISSUE THREAD

**Issue by hleduff** [react-pdf-viewer/react-pdf-viewer#416]
Hi,

For me #300 has not been fixed or has been broken again later.

Firstly, onChangePage seems to be firing on document load. Or at least it fires before the user does anything: if you log it, you'll see it in your console upon opening your app. In my view this should not happen because I don't see the use. If you want to do something on document load, there's an event for that.

Then the onPageChange fires two to four times on every click of the previous / next buttons, with varying values (mostly the current page, current page +1 and current page -1). It also happens when using the jumpToPage plugin example you kindly provided.

**Comment by hleduff** [comment]
Hello @phuoc-ng,

Sorry to be a bother, but did you find the time to look into this?

I don't think I'm doing anything wrong in my app because the problem I'm describing happens even in the basic example provided in the package.

**Comment by esetnik** [comment]
I have the same issue as this still in the latest version.

**Comment by phuoc-ng** [comment]
@hleduff @esetnik @jkeruzec
The issue was fixed in the latest code, and will be included in the next v3.1.0.

Here is the screenshot of the [sample demo](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/default-layout-onpagechange/index.tsx)

_Before_
![Screen Shot 2022-01-14 at 06 13 15](https://user-images.githubusercontent.com/57786711/149436346-e3b3385a-e65c-4eb5-8b0a-3eaa665fb752.png)

_After_
![Screen Shot 2022-01-14 at 06 24 42](https://user-images.githubusercontent.com/57786711/149436364-2e058117-68b2-4e43-98c1-bde1c5739d4c.png)

**Comment by phuoc-ng** [comment]
@hleduff @esetnik @jkeruzec
The [v3.1.0](https://react-pdf-viewer.dev/updates/) is released. It fixes the issue. Please upgrade!
