### ISSUE TITLE
Drag And Drop enabled by default in Toolbar, cannot disable.

### ISSUE THREAD

**Issue by pateljoel** [react-pdf-viewer/react-pdf-viewer#608]
I was evaluating react-pdf-viewer for a product of mine that I’m going to incorporate with. I tested on all the basic operations and it works well. 

However upon finishing my tests, just to make sure, I noticed that when I imported '@react-pdf-viewer/core' and tried doing a drag-and-drop action, it still loaded a file locally even though I didn't explicitly load the [Drag And Drop Plugin](https://react-pdf-viewer.dev/plugins/drop/), which is a huge red flag in my opinion.

What is even more strange is that there is no way to disable drag and drop for this library or printing, keyboard shortcuts etc even in the tool bar, and I assume any plugin. 

Is there a way to disable drag-and-drop, printing, keyboard shortcuts or any action that is the default for this library?

Thanks.

**Comment by ReactDevOnline** [comment]
Register only necessary plugins, for example:
I extract a few instances from toolbarPluginInstance which I will be using: 
`            toolbarPluginInstance:
            {
                fullScreenPluginInstance,
                pageNavigationPluginInstance,
                printPluginInstance,
                zoomPluginInstance,
                ...plugins
            }`
Instead of registering the whole toolbar plugin instance, I register only those who are needed, for example:
`                plugins={[
                     zoomPluginInstance,
                     printPluginInstance,
                     pageNavigationPluginInstance,
                     getFilePluginInstance,
                     fullScreenPluginInstance
                 ]}`
This way I evade the unnecessary plugins. Hope this helped!

**Comment by phuoc-ng** [comment]
@pateljoel The `drop` plugin is enabled automatically by the `toolbar` plugin. 
Because the `toolbar` plugin doesn't use any component provided by the `drop` plugin, the issue can be fixed in the near future, so users have to register the `drop` plugin if they want to use it.

Beside that and the shortcuts, do you need anything else? If yes, please issues for me.

**Comment by pateljoel** [comment]
@ReactDevOnline Is there a full fledged example of this since I have learned from @phuoc-ng that it all the toolbar plugins are enabled automatically which isn't ideal.

**Comment by phuoc-ng** [comment]
@pateljoel In the latest code, the toolbar plugin doesn't include the drop plugin anymore.
I'll include the changes in the next 2.6.0.

Regarding the shortcuts, I created new issue #610 to track it.

**Comment by phuoc-ng** [comment]
@pateljoel 
[v2.6.0](https://react-pdf-viewer.dev/updates/) is released. 
It includes the improvements you requested:
* The toolbar plugin doesn't include the drop plugin by default
* There are options to turn off the shortcuts

Please upgrade.
