### ISSUE TITLE
Select Area not Text i.e. Single Bounding Box, treat selected area as image

### ISSUE THREAD

**Issue by cyogian** [react-pdf-viewer/react-pdf-viewer#660]
Is their a way to have a third selection mode where user can select a rectangular area instead of text?

**Comment by phuoc-ng** [comment]
Can you give me a screenshot or anything that demonstrates the feature? I am not clear about it.

**Comment by cyogian** [comment]
https://agentcooper.github.io/react-pdf-highlighter/

Something similar to this. On pressing Alt, We are able to Select Area. I think that would be easy for you to create, because you are already caculating the boanding box. You just need to add an option to turn off Text Selection and turn on Area Selection.

**Comment by matthewcdowell** [comment]
Also very interested in this feature

**Comment by phuocng** [comment]
@cyogian @matthewcdowell 
This feature request will be available in the next 3.8.0.

## Demo

https://user-images.githubusercontent.com/57786711/197375701-e3a3c05d-f759-48cb-9e3a-e946b9480737.mp4

**Comment by phuocng** [comment]
@cyogian @matthewcdowell
[v3.8.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade.

**Comment by SumanASudharsanan** [comment]
Hi @phuocng , any documentation, links on area selection as an image. stuck with this for a while. any leads wud be very helpful. Thanks in advance.

**Comment by phuocng** [comment]
@SumanASudharsanan 

In order to create area selection, you can hold the _Option_ key (on macOS), or _Ctrl_ (on Windows), click in the document and then move the cursor to form the area. See the screenshot below:

<img width="746" alt="Screenshot 2024-02-02 at 21 29 53" src="https://github.com/react-pdf-viewer/react-pdf-viewer/assets/57786711/98c91ca6-cec5-4742-b7e5-d027c8c012e9">

The `RenderHighlightTargetProps` and `RenderHighlightContentProps` types contain `previewImage` property which is base 64 encoded of image representing the area.
