### ISSUE TITLE
Getting the fileData after file load

### ISSUE THREAD

**Issue by IbrahimAlshorafah** [react-pdf-viewer/react-pdf-viewer#684]
I am testing this package and in my case trying to use the drop-in plugin, however I need to the get the fileUrl after the file is loaded, unfortunately I couldnt find this in any of parameters or promises in the PdfDocument returned in this event, I am not sure how may I get the loaded file url so I may convert it to other format .. I want to get it to change it to base64

**Comment by phuoc-ng** [comment]
@IbrahimAlshorafah 
Thank for the suggestion. Supporting this feature is easy.
What do you think about this proposal?

## Add `onOpenFile` to `dropPlugin`

```js
const dropPluginInstance = dropPlugin({
  onOpenFile,
});
```

The `onOpenFile` callback is called after dropping a file.

```js
const onOpenFile = (file: File) => {
  new Promise<Uint8Array>((resolve) => {
    const reader = new FileReader();
    reader.readAsArrayBuffer(file);
    reader.onload = (): void => {
        const bytes = new Uint8Array(reader.result as ArrayBuffer);
        resolve(bytes);
    };
  }).then((data) => {
    // `data` is `Uint8Array`
    // You can do whatever you want with the `data`
  });
};
```

## Add `onOpenFile` to `Viewer`

This is triggered when users load a document
* Passing new `fileUrl`
* Drop a file
* Open from the toolbar with the [open plugin](https://react-pdf-viewer.dev/plugins/open/)

```js
<Viewer onOpenFile={handleOpenFile} />
```

`handleOpenFile` has the signatue:

```js
import type { OpenFile } from '@react-pdf-viewer/core';

const handleOpenFile = (openFile: OpenFile) => {
  // openFile.name: Present the name of file
  // openFile.data: PdfJs.FileData which can be a string or Uint8Array
}
```

I prefer the second approach because 
* It covers 3 cases at the same time
* and we get the file data directly.
(The first approach requires to convert from `File` to `Uint8Array`).

**Comment by phuoc-ng** [comment]
Oh, I just look at the `onDocumentLoad` event. The third approach is to add more information to the `DocumentLoadEvent`:

```js
const handleDocumentLoad = (e: DocumentLoadEvent) => {
  // e.doc
  // e.file: OpenFile
};

<Viewer onDocumentLoad={handleDocumentLoad} />
``` 

This approach seems to be the best, because we don't have to provide new option as the second one.

**Comment by phuoc-ng** [comment]
@IbrahimAlshorafah 
The feature was implemented in the latest code. From the next v2.7.2, you will be able to access the opened file information:

```js
const handleDocumentLoad = (e: DocumentLoadEvent) => {
    console.log(e.file.name, e.file.data);
};

<Viewer onDocumentLoad={handleDocumentLoad} />;
```

**Comment by phuoc-ng** [comment]
@IbrahimAlshorafah 
[v2.7.2 is released](https://react-pdf-viewer.dev/updates/). Please upgrade.
