### ISSUE TITLE
Metadata of Authors does not show all authos when seperate by a semicolon

### ISSUE THREAD

**Issue by Braweria** [react-pdf-viewer/react-pdf-viewer#805]
Hey,

I just downloaded this PDF to test possibilities of the library  
https://www.researchgate.net/publication/350106110_Maternal_and_neonatal_health_care_worker_well-being_and_patient_safety_climate_amid_the_COVID-19_pandemic/link/6089d927458515d315e308a3/download

And noticed that it doesn't show all authors, only the first. The only difference I found between this one, and other PDFs was, that it uses semicolon to separate the authors.

![image](https://user-images.githubusercontent.com/62669899/135857866-26f3f451-1264-483e-a798-5b6ec34271f4.png)
![image](https://user-images.githubusercontent.com/62669899/135857903-efdec9a6-1454-4daa-a1d4-dbc7b49c947f.png)

Is this something that will be addressed or is this not possible somehow?

**Comment by phuoc-ng** [comment]
@Braweria 
The `Author` value is taken from the `Author` property of the document's info, as we see in the second screenshot you gave above. It's not caused by the separator.

I tried to open the document with another viewers. They all display the author as following:

_Previewer (macOS)_
![Screen Shot 2021-10-04 at 20 36 07](https://user-images.githubusercontent.com/57786711/135861607-ac71f2f7-0a3b-4df6-a59d-707d957997a8.png)

_Chrome_

![Screen Shot 2021-10-04 at 20 36 33](https://user-images.githubusercontent.com/57786711/135861683-b0aa8401-d202-4380-9e1d-dc62db531e7e.png)

_Firefox_

![Screen Shot 2021-10-04 at 20 40 52](https://user-images.githubusercontent.com/57786711/135861875-ed08e210-b4cc-498e-9904-7ef86d31984d.png)

However, the `metadata` of the document indicates that it has 8 authors under the `dc:creator` property:

![Screen Shot 2021-10-04 at 20 41 48](https://user-images.githubusercontent.com/57786711/135862034-8e5fcac7-a93e-4289-9ddc-16c377391187.png)

So, it's possible to fix this issue, but I don't think replacing `Author` field with `dc:creator` is correct.
Maybe I will add another section named `metadata` to list addition properties. What do you think?

**Comment by Braweria** [comment]
I believe this is reading it incorrectly. I have checked Firefox, too, and it shows the same way as your screenshot.  
My Screenshot from before was from Adobe Acrobat Pro DC. This is how I add authors to a PDF, which si separate by semicolon automatically by Acrobat Reader.

![image](https://user-images.githubusercontent.com/62669899/135873074-24517c7f-88ac-4682-bd88-d13957e0b91a.png)

And here is what I get when reading the metadata:

![image](https://user-images.githubusercontent.com/62669899/135868772-4e564e6a-a7f5-471b-b4f3-46f54a0451a2.png)

This is from Vivaldi, a chromium-based browser.

![image](https://user-images.githubusercontent.com/62669899/135869331-cb0f9951-42e3-4689-a9b0-9749a60fdbcf.png)

And this is Google Chrome.

In both you can see, that only the first name listed as Author was taken, but not the others. You can also see, that `dc:creators` is a string and not an array like in your example, but that might be the devtools not showing it correctly, I haveb't ventured into that part yet.

**Comment by Braweria** [comment]
I'm also not sure if it is just a limitation of reading the PDF file. I also don't know of a good solution for it, if I come up with anything, I will comment again.

**Comment by phuoc-ng** [comment]
I think in that case, you can pick the `dc:creator` to show to your users. It's up to you to do whatever you want with the metadata.

**Comment by Braweria** [comment]
> I think in that case, you can pick the `dc:creator` to show to your users. It's up to you to do whatever you want with the metadata.
@phuoc-ng 

I tried getting the creator, but it is a string for me, and not an array, like in your screenshot.

This is how I get it:
```js
console.log(metaData.metadata._metadataMap.get('dc:creator'));
```
And this is what I get
> Eman HaidariElliott K. MainXin CuiValerie CapeDaniel S. TawfikKathryn C. AdairBryan J. SextonJochen Profit
![image](https://user-images.githubusercontent.com/62669899/135990671-29a677d1-c14e-420b-bc3d-ebb6e6d839ba.png)

These are the versions I am using:
```js
    "@react-pdf-viewer/core": "2.9.1",
    "@react-pdf-viewer/default-layout": "^2.9.1",
    "@react-pdf-viewer/highlight": "^2.9.1",
    "pdfjs-dist": "2.6.347",
```
And React v17 and Next v11.

**Comment by phuoc-ng** [comment]
My `pdfjs-dist` is `2.9.359`. You can try to upgrade it.

**Comment by Braweria** [comment]
> My `pdfjs-dist` is `2.9.359`. You can try to upgrade it.

Updating it worked out great.   
Can I suggest to update the "Getting Started" on the website? It uses the version I had previously. The way it was described, makes it sound, that react-pdf-viewer worked well with this version of pdfjs-dist.

**Comment by phuoc-ng** [comment]
Please see https://react-pdf-viewer.dev/docs/getting-started/

![Screen Shot 2021-10-05 at 16 20 33](https://user-images.githubusercontent.com/57786711/135996237-837b7189-208d-49f3-853c-f695f0f3619f.png)

**Comment by Braweria** [comment]
Well, now I feel ridiculous. 😅  
Big thanks for the help, my issue is resolved now!

**Comment by phuoc-ng** [comment]
Feel free to create more issues. It's the only way I can make the library better.
