### ISSUE TITLE
Thumbnail stuck on loading

### ISSUE THREAD

**Issue by fwara07** [react-pdf-viewer/react-pdf-viewer#874]
Hello,

When I am trying to render a pdf, the thumbnail tab in the sidebar is stuck on a loading screen. When I took a look at the console, I saw that there was the following error concerning the `ThumbnailListWithStore` and the `ThumbnailsDecorator` : 

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at ThumbnailListWithStore (http://localhost:3000/_next/static/chunks/pages/analyse/%5Bid%5D.js?ts=1637292631538:30386:37)
    at ThumbnailsDecorator
```

Here my code rendering the pdf: 

```
<div className="w-full p-0 h-screen overflowx-hidden bg-white rounded-lg shadow-md">
  <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
    {pdfUrl === '' || pdfUrl === undefined || pdfUrl === null ? (
      <h2 className="text-2xl font-bold leading-7 text-gray-800 sm:text-3xl sm:leading-9 sm:truncate"></h2>
    ) : (
      <Viewer
        fileUrl={pdfUrl}
        plugins={[defaultLayoutPluginInstance, highlightPluginInstance]}
        onDocumentLoad={handleDocumentLoad}
      />
    )}
  </Worker>
</div>
```

I am using tailwind css, if ever that is information is useful.

If anyone knows the solution, it would be greatly appreciated!

**Comment by matthewcdowell** [comment]
I ran into the same error but am using API/pdfjs-dist version 2.10.377 and the latest version of react-pdf-viewer (2.11.0). I'm using on a react/django/mysql stack. My short term hack/bypass was to pass a plugin with a custom sidebar (and toolbar) and mute/remove the offending components. In my case it was both the thumbnail in the sidebar as well as the CurrentPageInput and NumberOfPages components. Still have no idea why it's happening--the error appeared after updating some packages and completely broke my app. 

Will post code if relevant but my sense is in order to really figure out what's going on may need to create a separate minimalist build/environment which replicates the error.

I've Googled this issue extensively and changed countless parts of my code to try to get different behavior to no avail. Ultimately just ended up hiding the problem to deal with later in hopes that it resolves itself in future updates.

**Comment by fwara07** [comment]
I see, thanks for your quick response. I am researching this error as well, and will post if ever I have a solution, but right now, I also have no idea how to fix this issue.

**Comment by fwara07** [comment]
Did anyone find a fix for this issue?

**Comment by phuoc-ng** [comment]
Updated: The issue was fixed in the latest code. The fix will be included in the next version.

## Before the fix

Clicking the `Trigger re-render` will cause the thumbnails are stuck at loading spinner.

[Sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/thumbnail-stuck-loading/index.tsx)

https://user-images.githubusercontent.com/57786711/142731110-e67f4c6a-1695-4067-9950-f6c4ccf0d126.mp4

## After the fix

https://user-images.githubusercontent.com/57786711/142731135-d0bdba4a-b69d-4d9f-9128-9621e320b792.mp4

**Comment by fwara07** [comment]
Thanks for your reply, do you perhaps know when the next version will come out?

**Comment by phuoc-ng** [comment]
@fwara07 @matthewcdowell
[v3.0.0](https://react-pdf-viewer.dev/updates/) was released. Please upgrade!

**Comment by phuoc-ng** [comment]
cc @timur-pimkin-finsight
