### ISSUE TITLE
Specific PDF file not loading (blank pages)

### ISSUE THREAD

**Issue by LucasBer** [react-pdf-viewer/react-pdf-viewer#909]
Hi,

I've been using this library for loading/rendering multiple PDF's with no problems. However, a specific file that has been supplied to me doesn't render with the react-pdf-viewer library, and I'm not sure why this is happening. 

When trying to render this specific PDF, the viewer keeps loading, showing white pages and the thumbnails appear to be continuously loading as well.  

No errors are being logged to the console. 

Here's some extra information:
- To test the core functionality of simply loading the PDF I've been using the [NextJS starter project.](https://github.com/react-pdf-viewer/starter/tree/main/nextjs) I simply add the PDF to the Viewer as a property.
- Testing with [the PDF.js online demo](https://mozilla.github.io/pdf.js/web/viewer.html) (and some other PDF viewers) works fine. I have no problems loading the PDF there.
- I have tried messing around with some of the Viewer properties, such as adding characterMaps or adding a renderError function to log possible output, but nothing has yielded a result so far. 
- The onDocumentLoad property on the Viewer gets triggered, meaning the Viewer considers the PDF as "loaded"

Since I've not been able to figure out what the issue is, and since no errors are being thrown I'm asking the question here;

What is causing this behavior? 

I've attached an example PDF of 1 single page from the document. This specific PDF is not loading for me.

![image](https://user-images.githubusercontent.com/32563741/144767854-e0b3515e-b09c-4006-bc17-9ea844d17b53.png)

### Example PDF
**[example.pdf](https://github.com/react-pdf-viewer/react-pdf-viewer/files/7656956/example.pdf)**

**Comment by phuoc-ng** [comment]
Hi @LucasBer,

Thanks for reporting the issue. After a few tries of debugging, I realized that the issue is caused by pdf-js, the library we're using to render PDF documents.

I upgraded [this example](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) to the latest version of pdf-js (`2.11.338`), and it works!

![Screen Shot 2021-12-07 at 17 13 59](https://user-images.githubusercontent.com/57786711/145010638-cb036283-94d5-4484-a666-5b6b4531d714.png)

Can you give it a try?
