### ISSUE TITLE
Thumbnail Plugin: Duplicate Cover Images

### ISSUE THREAD

**Issue by robhung** [react-pdf-viewer/react-pdf-viewer#934]
Hello! Extending from #892

Running into an issue with latest version (3.0.0) where if I have multiple different PDF Cover's on the same page, the first one to finish loading becomes the cover image for all PDF's.

It worked fine in version <3.0.0 when it was `canvas` (but I do prefer `img` as it can now resize without needing to re-render).

We're using the exact same code from this [example](https://react-pdf-viewer.dev/examples/display-the-thumbnail-of-a-given-page/).

---

I'm reading the source code and can see that `CoverInner` generates the `src` for `img` based on what `doc` is loaded from the `store`. When a document is loaded, it runs `onDocumentLoad` to update the `store`.

The bug I'm experiencing is that all images get the same `src`, even if the `fileUrl` passed into each `Viewer` is different. Is it somehow using the same store, or am I not rendering them correctly?

Thought I might quickly report it first in case it's easily reproducible, otherwise let me know if you need me to sandbox it! (Haven't quite figured out if it's an issue with the library or our own code)

**Comment by sudheer-ranga** [comment]
+1 facing the same issue

**Comment by phuoc-ng** [comment]
This will be fixed in the next v3.1.0.

**Comment by phuoc-ng** [comment]
Updated: The issue was fixed in the latest code, and will be included in the next release.

Here is screenshot when using this [sample code](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/thumbnail-cover/index.tsx)

![Screen Shot 2021-12-25 at 11 56 41](https://user-images.githubusercontent.com/57786711/147377925-ed0ff041-96af-4bab-bc95-af89f0677c1d.png)

**Comment by robhung** [comment]
Can't wait, this is what's blocking us from upgrading to `3.x.x` - thanks @phuoc-ng !!
